# Generated by Django 5.0.6 on 2024-06-10 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_tag_articletag_article_scopes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='articletag',
            options={'verbose_name': 'Раздел для статьи', 'verbose_name_plural': 'Разделы для статьи'},
        ),
        migrations.AlterField(
            model_name='articletag',
            name='is_main',
            field=models.BooleanField(verbose_name='Основной раздел?'),
        ),
    ]
