# Generated by Django 5.0.6 on 2024-06-14 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_alter_articletag_options_alter_articletag_is_main'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-published_at'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.RenameField(
            model_name='article',
            old_name='scopes',
            new_name='tags',
        ),
    ]
